import jsPDF from 'jspdf';
import { WebsiteAnalysis } from '@/types';
import { SCORING_FACTORS } from '@/lib/scoring/config';

export function generateMarkdownReport(analysis: WebsiteAnalysis): string {
  const date = new Date(analysis.timestamp).toLocaleDateString();

  const factorRows = SCORING_FACTORS.map((factor) => {
    const result = analysis.factors[factor.key];
    return `| **${factor.label}** | ${result.score}% | ${result.status} | ${Math.round(factor.weight * 100)}% |`;
  }).join('\n');

  const factorSections = SCORING_FACTORS.map((factor) => {
    const result = analysis.factors[factor.key];
    const findings = result.findings.length > 0
      ? result.findings.map((finding) => `- ${finding}`).join('\n')
      : '- No major issues detected.';

    const recommendations = result.recommendations.length > 0
      ? result.recommendations.map((rec) => `- **${rec.priority.toUpperCase()}**: ${rec.text}${rec.timeToImplement ? ` (${rec.timeToImplement})` : ''}`).join('\n')
      : '- No recommendations for this factor.';

    return `## ${result.label} (${result.score}%)\n\n### Findings\n${findings}\n\n### Recommendations\n${recommendations}\n`;
  }).join('\n');

  const priorityRecommendations = analysis.recommendations
    .map((rec) => `- **${rec.priority.toUpperCase()}** (${rec.category}): ${rec.text}${rec.timeToImplement ? ` (${rec.timeToImplement})` : ''}`)
    .join('\n');

  return `# AI Website Grader Report\n\n**Website:** ${analysis.url}  \n**Title:** ${analysis.title}  \n**Generated:** ${date}  \n**Overall Score:** ${analysis.overallScore}%\n\n## 4-Factor Score Breakdown\n\n| Factor | Score | Status | Weight |\n|---|---:|---|---:|\n${factorRows}\n\n## Priority Recommendations\n${priorityRecommendations || '- No recommendations generated.'}\n\n${factorSections}\n\n---\nThis report evaluates one page URL (not the entire site) using the v3 4-factor model.`;
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function generatePDFReport(analysis: WebsiteAnalysis): Promise<void> {
  if (typeof window === 'undefined') {
    throw new Error('PDF generation is only available in the browser');
  }

  const pdf = new jsPDF('p', 'mm', 'a4');
  const brandGreen = '#1B7340';
  const margin = 16;
  const maxWidth = 178;
  const pageHeight = 297;
  const footerText = 'Generated by AI Website Grader | searchinfluence.com';
  const generatedDate = new Date(analysis.timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  let y = 34;

  const drawFooter = () => {
    pdf.setDrawColor(219, 229, 223);
    pdf.line(margin, pageHeight - 13, 210 - margin, pageHeight - 13);
    pdf.setTextColor(95, 108, 104);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.text(footerText, margin, pageHeight - 8);
  };

  const addPage = () => {
    drawFooter();
    pdf.addPage();
    y = 24;
  };

  const ensureSpace = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - 20) {
      addPage();
    }
  };

  const writeLine = (text: string, size = 10, bold = false, color = '#24323F') => {
    pdf.setFont('helvetica', bold ? 'bold' : 'normal');
    pdf.setFontSize(size);
    pdf.setTextColor(color);
    const lines = pdf.splitTextToSize(text, maxWidth);

    lines.forEach((line: string) => {
      ensureSpace(size <= 10 ? 6 : 8);
      pdf.text(line, margin, y);
      y += size <= 10 ? 5.4 : 7;
    });
  };

  const writeSectionHeader = (title: string) => {
    ensureSpace(14);
    pdf.setDrawColor(203, 216, 209);
    pdf.line(margin, y - 3, 210 - margin, y - 3);
    writeLine(title, 13, true, brandGreen);
  };

  const logoDataUrl = await tryLoadLogoDataUrl('/si-logo.png');
  if (logoDataUrl) {
    pdf.addImage(logoDataUrl, 'PNG', margin, 10, 38, 11);
  } else {
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(14);
    pdf.setTextColor(brandGreen);
    pdf.text('Search Influence', margin, 17);
  }

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.setTextColor(84, 96, 109);
  pdf.text(`Generated: ${generatedDate}`, 210 - margin, 17, { align: 'right' });

  writeLine('AI Website Grader Report', 18, true, '#1E2F3A');
  writeLine(`Website: ${analysis.url}`, 10);
  writeLine(`Title: ${analysis.title || 'Untitled page'}`, 10);
  y += 2;

  ensureSpace(20);
  pdf.setFillColor(236, 245, 240);
  pdf.setDrawColor(193, 215, 201);
  pdf.roundedRect(margin, y, maxWidth, 18, 2, 2, 'FD');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor(58, 74, 89);
  pdf.text('Overall Score', margin + 4, y + 7);
  pdf.setFontSize(18);
  pdf.setTextColor(brandGreen);
  pdf.text(`${analysis.overallScore}%`, margin + 4, y + 14);
  y += 24;

  writeSectionHeader('Score Summary');
  SCORING_FACTORS.forEach((factor) => {
    const result = analysis.factors[factor.key];
    writeLine(
      `${factor.label}: ${result.score}% (${result.status}) | Weight ${Math.round(factor.weight * 100)}%`,
      10
    );
  });

  y += 2;
  writeSectionHeader('Top Recommendations');
  const topRecommendations = analysis.recommendations.slice(0, 10);
  if (topRecommendations.length === 0) {
    writeLine('No recommendations generated.', 10);
  } else {
    topRecommendations.forEach((rec, idx) => {
      writeLine(`${idx + 1}. [${rec.priority.toUpperCase()}] ${rec.text}`, 10);
      if (rec.timeToImplement) {
        writeLine(`   Time to implement: ${rec.timeToImplement}`, 9, false, '#5A6874');
      }
    });
  }

  addPage();
  writeSectionHeader('Factor Breakdowns');
  SCORING_FACTORS.forEach((factor, factorIndex) => {
    const result = analysis.factors[factor.key];
    if (factorIndex > 0) {
      ensureSpace(14);
      pdf.setDrawColor(229, 234, 238);
      pdf.line(margin, y - 2, 210 - margin, y - 2);
    }
    writeLine(`${result.label} (${result.score}%)`, 12, true, '#1E2F3A');
    if (result.findings.length === 0) {
      writeLine('Findings: No major issues detected.', 10);
    } else {
      writeLine('Findings:', 10, true);
      result.findings.slice(0, 5).forEach((finding) => writeLine(`- ${finding}`, 10));
    }
    if (result.recommendations.length > 0) {
      writeLine('Recommendations:', 10, true);
      result.recommendations.slice(0, 3).forEach((rec) => writeLine(`- ${rec.text}`, 10));
    }
    y += 3;
  });

  drawFooter();
  pdf.save(`ai-grader-report-${analysis.url.replace(/[^a-z0-9]/gi, '-')}.pdf`);
}

async function tryLoadLogoDataUrl(src: string): Promise<string | null> {
  if (typeof window === 'undefined') return null;

  return new Promise((resolve) => {
    const image = new Image();
    image.crossOrigin = 'anonymous';
    image.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const context = canvas.getContext('2d');
        if (!context) {
          resolve(null);
          return;
        }
        context.drawImage(image, 0, 0);
        resolve(canvas.toDataURL('image/png'));
      } catch {
        resolve(null);
      }
    };
    image.onerror = () => resolve(null);
    image.src = src;
  });
}
