import jsPDF from 'jspdf';
import { WebsiteAnalysis } from '@/types';
import { SCORING_FACTORS } from '@/lib/scoring/config';

export function generateMarkdownReport(analysis: WebsiteAnalysis): string {
  const date = new Date(analysis.timestamp).toLocaleDateString();

  const factorRows = SCORING_FACTORS.map((factor) => {
    const result = analysis.factors[factor.key];
    return `| **${factor.label}** | ${result.score}% | ${result.status} | ${Math.round(factor.weight * 100)}% |`;
  }).join('\n');

  const factorSections = SCORING_FACTORS.map((factor) => {
    const result = analysis.factors[factor.key];
    const findings = result.findings.length > 0
      ? result.findings.map((finding) => `- ${finding}`).join('\n')
      : '- No major issues detected.';

    const recommendations = result.recommendations.length > 0
      ? result.recommendations.map((rec) => `- **${rec.priority.toUpperCase()}**: ${rec.text}${rec.timeToImplement ? ` (${rec.timeToImplement})` : ''}`).join('\n')
      : '- No recommendations for this factor.';

    return `## ${result.label} (${result.score}%)\n\n### Findings\n${findings}\n\n### Recommendations\n${recommendations}\n`;
  }).join('\n');

  const priorityRecommendations = analysis.recommendations
    .map((rec) => `- **${rec.priority.toUpperCase()}** (${rec.category}): ${rec.text}${rec.timeToImplement ? ` (${rec.timeToImplement})` : ''}`)
    .join('\n');

  return `# AI Website Grader Report\n\n**Website:** ${analysis.url}  \n**Title:** ${analysis.title}  \n**Generated:** ${date}  \n**Overall Score:** ${analysis.overallScore}%\n\n## 4-Factor Score Breakdown\n\n| Factor | Score | Status | Weight |\n|---|---:|---|---:|\n${factorRows}\n\n## Priority Recommendations\n${priorityRecommendations || '- No recommendations generated.'}\n\n${factorSections}\n\n---\nThis report evaluates one page URL (not the entire site) using the v3 4-factor model.`;
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function generatePDFReport(analysis: WebsiteAnalysis): Promise<void> {
  if (typeof window === 'undefined') {
    throw new Error('PDF generation is only available in the browser');
  }

  const pdf = new jsPDF('p', 'mm', 'a4');
  // SI Brand Colors
  const siDarkNavy = '#012c3a';
  const siNavy = '#014a61';
  const siMediumBlue = '#3490b5';
  const siLightBlue = '#4eb1cd';
  const siGreen = '#91c364';
  const siOrange = '#df5926';
  const margin = 16;
  const maxWidth = 178;
  const pageHeight = 297;
  const pageWidth = 210;
  const footerText = 'Generated by AI Website Grader  •  searchinfluence.com';
  const generatedDate = new Date(analysis.timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  let y = 0;
  const logoDataUrl = await tryLoadLogoDataUrl('/search-influence-logo.png');

  // Helper: hex to RGB
  const hexToRgb = (hex: string) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return { r, g, b };
  };

  // Helper: score color using SI palette
  const getScoreColor = (score: number): string => {
    if (score >= 80) return siGreen;
    if (score >= 60) return siMediumBlue;
    if (score >= 40) return siOrange;
    return '#c0392b';
  };

  // Helper: draw branded header bar
  const drawPageHeader = (isFirstPage = false) => {
    // Dark navy header bar
    const headerHeight = isFirstPage ? 42 : 18;
    const navyRgb = hexToRgb(siDarkNavy);
    pdf.setFillColor(navyRgb.r, navyRgb.g, navyRgb.b);
    pdf.rect(0, 0, pageWidth, headerHeight, 'F');

    // Accent line under header
    const greenRgb = hexToRgb(siGreen);
    pdf.setFillColor(greenRgb.r, greenRgb.g, greenRgb.b);
    pdf.rect(0, headerHeight, pageWidth, 1.5, 'F');

    if (logoDataUrl) {
      // Logo: 1748x373 = 4.68:1 ratio. Height 9mm → width ~42mm
      const logoH = isFirstPage ? 10 : 8;
      const logoW = logoH * (1748 / 373);
      const logoY = isFirstPage ? 8 : 5;
      pdf.addImage(logoDataUrl, 'PNG', margin, logoY, logoW, logoH);
    } else {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(isFirstPage ? 16 : 12);
      pdf.setTextColor(255, 255, 255);
      pdf.text('Search Influence', margin, isFirstPage ? 16 : 12);
    }

    if (isFirstPage) {
      // Title text on header
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(18);
      pdf.setTextColor(255, 255, 255);
      pdf.text('AI Website Grader Report', margin, 30);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      const blueRgb = hexToRgb(siLightBlue);
      pdf.setTextColor(blueRgb.r, blueRgb.g, blueRgb.b);
      pdf.text('AI SEO Performance Summary', margin, 37);
    }

    // Date right-aligned
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(200, 215, 225);
    pdf.text(generatedDate, pageWidth - margin, isFirstPage ? 37 : 12, { align: 'right' });

    y = headerHeight + 6;
  };

  // Helper: branded footer
  const drawFooter = () => {
    const navyRgb = hexToRgb(siNavy);
    pdf.setFillColor(navyRgb.r, navyRgb.g, navyRgb.b);
    pdf.rect(0, pageHeight - 14, pageWidth, 14, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.text(footerText, margin, pageHeight - 6);
    pdf.text('Confidential', pageWidth - margin, pageHeight - 6, { align: 'right' });
  };

  const addPage = () => {
    drawFooter();
    pdf.addPage();
    drawPageHeader(false);
  };

  const ensureSpace = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - 22) {
      addPage();
    }
  };

  const writeLine = (text: string, size = 10, bold = false, color = '#24323F', indent = 0) => {
    pdf.setFont('helvetica', bold ? 'bold' : 'normal');
    pdf.setFontSize(size);
    pdf.setTextColor(color);
    const lineMaxWidth = maxWidth - indent;
    const lines = pdf.splitTextToSize(text, lineMaxWidth);

    lines.forEach((line: string) => {
      ensureSpace(size <= 10 ? 6 : 8);
      pdf.text(line, margin + indent, y);
      y += size <= 10 ? 5.4 : 7;
    });
  };

  const writeSectionHeader = (title: string) => {
    ensureSpace(16);
    y += 2;
    // Colored accent bar
    const blueRgb = hexToRgb(siMediumBlue);
    pdf.setFillColor(blueRgb.r, blueRgb.g, blueRgb.b);
    pdf.rect(margin, y - 4, 4, 8, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(14);
    pdf.setTextColor(siDarkNavy);
    pdf.text(title, margin + 8, y + 2);
    y += 10;
  };

  // ─── PAGE 1: Cover + Score ───
  drawPageHeader(true);
  y += 4;

  // Website info card
  const cardY = y;
  const cardHeight = 22;
  pdf.setFillColor(248, 250, 252);
  pdf.setDrawColor(222, 230, 237);
  pdf.roundedRect(margin, cardY, maxWidth, cardHeight, 3, 3, 'FD');
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(siNavy);
  pdf.text(`Website:  ${analysis.url}`, margin + 6, cardY + 8);
  pdf.text(`Title:  ${analysis.title || 'Untitled page'}`, margin + 6, cardY + 15);
  y = cardY + cardHeight + 8;

  // Overall score — big visual element
  ensureSpace(55);
  const scoreBoxY = y;
  const scoreColor = getScoreColor(analysis.overallScore);
  const scoreRgb = hexToRgb(scoreColor);

  // Score circle
  const circleX = margin + 30;
  const circleY = scoreBoxY + 22;
  const circleR = 18;
  pdf.setDrawColor(scoreRgb.r, scoreRgb.g, scoreRgb.b);
  pdf.setLineWidth(2.5);
  pdf.circle(circleX, circleY, circleR);
  pdf.setLineWidth(0.2);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(28);
  pdf.setTextColor(scoreColor);
  const scoreText = `${analysis.overallScore}`;
  pdf.text(scoreText, circleX, circleY - 2, { align: 'center' });
  pdf.setFontSize(10);
  pdf.text('/ 100', circleX, circleY + 6, { align: 'center' });

  // Score label
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(13);
  pdf.setTextColor(siDarkNavy);
  pdf.text('Overall AI Readiness Score', margin + 56, scoreBoxY + 10);

  // Score interpretation
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor('#4d5966');
  const scoreInterpretation = analysis.overallScore >= 80
    ? 'Excellent — This site is well-optimized for AI search engines.'
    : analysis.overallScore >= 60
      ? 'Good — Solid foundation with room for improvement.'
      : analysis.overallScore >= 40
        ? 'Needs Work — Several areas require attention for AI visibility.'
        : 'Critical — Major gaps in AI search readiness.';
  pdf.text(scoreInterpretation, margin + 56, scoreBoxY + 18);

  // Mini factor bars
  const barStartX = margin + 56;
  const barWidth = 100;
  const barHeight = 5;
  let barY = scoreBoxY + 26;
  SCORING_FACTORS.forEach((factor) => {
    const result = analysis.factors[factor.key];
    const factorColor = getScoreColor(result.score);
    const factorRgb = hexToRgb(factorColor);

    // Label
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor('#4d5966');
    pdf.text(factor.label, barStartX, barY - 1);
    pdf.text(`${result.score}%`, barStartX + barWidth + 3, barY - 1);

    // Background bar
    pdf.setFillColor(235, 240, 245);
    pdf.roundedRect(barStartX, barY, barWidth, barHeight, 1.5, 1.5, 'F');

    // Score bar
    const filledWidth = Math.max(2, (result.score / 100) * barWidth);
    pdf.setFillColor(factorRgb.r, factorRgb.g, factorRgb.b);
    pdf.roundedRect(barStartX, barY, filledWidth, barHeight, 1.5, 1.5, 'F');

    barY += 11;
  });
  y = Math.max(scoreBoxY + 45, barY + 4);

  // ─── Score Breakdown Table ───
  writeSectionHeader('Score Breakdown');

  // Table header
  const colWidths = [75, 30, 38, 35];
  const tableX = margin;
  const navyRgb = hexToRgb(siDarkNavy);
  pdf.setFillColor(navyRgb.r, navyRgb.g, navyRgb.b);
  pdf.rect(tableX, y - 4, maxWidth, 9, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.setTextColor(255, 255, 255);
  let colX = tableX + 4;
  ['Factor', 'Score', 'Status', 'Weight'].forEach((header, i) => {
    pdf.text(header, colX, y + 2);
    colX += colWidths[i];
  });
  y += 9;

  // Table rows
  SCORING_FACTORS.forEach((factor, idx) => {
    const result = analysis.factors[factor.key];
    ensureSpace(10);
    if (idx % 2 === 0) {
      pdf.setFillColor(245, 248, 252);
      pdf.rect(tableX, y - 4, maxWidth, 9, 'F');
    }
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    colX = tableX + 4;
    pdf.setTextColor(siDarkNavy);
    pdf.text(factor.label, colX, y + 2);
    colX += colWidths[0];
    const fColor = getScoreColor(result.score);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(fColor);
    pdf.text(`${result.score}%`, colX, y + 2);
    colX += colWidths[1];
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor('#4d5966');
    const statusLabel = result.status.charAt(0).toUpperCase() + result.status.slice(1);
    pdf.text(statusLabel, colX, y + 2);
    colX += colWidths[2];
    pdf.text(`${Math.round(factor.weight * 100)}%`, colX, y + 2);
    y += 9;
  });
  y += 4;

  // ─── Top Recommendations ───
  writeSectionHeader('Top Recommendations');
  const topRecommendations = analysis.recommendations.slice(0, 10);
  if (topRecommendations.length === 0) {
    writeLine('No recommendations generated.', 10);
  } else {
    topRecommendations.forEach((rec, idx) => {
      ensureSpace(14);
      // Priority badge
      const priorityColor = rec.priority === 'high' ? siOrange : rec.priority === 'medium' ? siMediumBlue : siGreen;
      const prRgb = hexToRgb(priorityColor);
      pdf.setFillColor(prRgb.r, prRgb.g, prRgb.b);
      pdf.roundedRect(margin, y - 3.5, 16, 5.5, 1.5, 1.5, 'F');
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(7);
      pdf.setTextColor(255, 255, 255);
      pdf.text(rec.priority.toUpperCase(), margin + 1.5, y);

      // Recommendation text
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9.5);
      pdf.setTextColor('#24323F');
      const recLines = pdf.splitTextToSize(`${idx + 1}. ${rec.text}`, maxWidth - 22);
      recLines.forEach((line: string, lineIdx: number) => {
        pdf.text(line, margin + 19, y + (lineIdx * 4.5));
      });
      y += Math.max(7, recLines.length * 4.5) + 2;

      if (rec.timeToImplement) {
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(8);
        pdf.setTextColor('#7f8c8d');
        pdf.text(`Est. ${rec.timeToImplement}`, margin + 19, y - 1);
        y += 3;
      }
    });
  }

  // ─── Factor Breakdowns ───
  addPage();
  writeSectionHeader('Detailed Factor Analysis');
  SCORING_FACTORS.forEach((factor, factorIndex) => {
    const result = analysis.factors[factor.key];
    const factorScoreColor = getScoreColor(result.score);

    ensureSpace(30);
    if (factorIndex > 0) {
      y += 2;
      pdf.setDrawColor(222, 230, 237);
      pdf.setLineWidth(0.3);
      pdf.line(margin, y - 2, pageWidth - margin, y - 2);
      y += 4;
    }

    // Factor header with score badge
    const fRgb = hexToRgb(factorScoreColor);
    pdf.setFillColor(fRgb.r, fRgb.g, fRgb.b);
    pdf.roundedRect(margin, y - 4, 14, 7, 2, 2, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(9);
    pdf.setTextColor(255, 255, 255);
    pdf.text(`${result.score}%`, margin + 1.5, y + 0.5);

    pdf.setFontSize(12);
    pdf.setTextColor(siDarkNavy);
    pdf.text(result.label, margin + 18, y + 1);
    y += 9;

    if (result.findings.length === 0) {
      writeLine('No major issues detected.', 9, false, '#5b6775', 4);
    } else {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(9);
      pdf.setTextColor(siNavy);
      pdf.text('Findings', margin + 4, y);
      y += 5;
      result.findings.slice(0, 5).forEach((finding) => {
        writeLine(`•  ${finding}`, 9, false, '#3a4a59', 6);
      });
    }
    if (result.recommendations.length > 0) {
      y += 2;
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(9);
      pdf.setTextColor(siNavy);
      pdf.text('Recommendations', margin + 4, y);
      y += 5;
      result.recommendations.slice(0, 3).forEach((rec) => {
        writeLine(`→  ${rec.text}`, 9, false, '#3a4a59', 6);
      });
    }
    y += 3;
  });

  // ─── CTA Footer ───
  // Only add CTA if it fits on the current page; skip if it would create a mostly-empty page
  const ctaHeight = 26; // 4 padding + 22 box
  const spaceLeft = pageHeight - 22 - y; // 22 = footer height buffer
  if (spaceLeft < ctaHeight) {
    // Not enough room — draw the CTA inline in the footer area instead of forcing a new page
    drawFooter();
    pdf.save(`ai-grader-report-${analysis.url.replace(/[^a-z0-9]/gi, '-')}.pdf`);
    return;
  }
  y += 4;
  const ctaY = y;
  const blueRgb = hexToRgb(siMediumBlue);
  pdf.setFillColor(blueRgb.r, blueRgb.g, blueRgb.b);
  pdf.roundedRect(margin, ctaY, maxWidth, 22, 3, 3, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Ready to improve your AI search visibility?', margin + 8, ctaY + 9);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text('Contact Search Influence for a comprehensive AI SEO strategy.  →  searchinfluence.com', margin + 8, ctaY + 16);

  drawFooter();
  pdf.save(`ai-grader-report-${analysis.url.replace(/[^a-z0-9]/gi, '-')}.pdf`);
}

async function tryLoadLogoDataUrl(src: string): Promise<string | null> {
  if (typeof window === 'undefined') return null;

  return new Promise((resolve) => {
    const image = new Image();
    image.crossOrigin = 'anonymous';
    image.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const context = canvas.getContext('2d');
        if (!context) {
          resolve(null);
          return;
        }
        context.drawImage(image, 0, 0);
        resolve(canvas.toDataURL('image/png'));
      } catch {
        resolve(null);
      }
    };
    image.onerror = () => resolve(null);
    image.src = src;
  });
}
